export const SWITCH_SCREEN = 'SWITCH_SCREEN';

export const RESIZE_VIEWPORT = 'RESIZE_VIEWPORT';

export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';

export const CHANGE_BALANCE = 'CHANGE_BALANCE';

export const CHANGE_SUBSCRIPTION = 'CHANGE_SUBSCRIPTION';

export const UPDATE_BALANCE_HISTORY = 'UPDATE_BALANCE_HISTORY';

export const SET_LOADER = 'SET_LOADER';

export const SET_MESSAGE = 'SET_MESSAGE';